name: QUIC Interop

run-name: Execute ${{ github.event.inputs.testcase }} on ${{ github.event.inputs.client }}

on: 
  workflow_dispatch:
    inputs:
      testcase:
        type: choice
        description: Choose testcase
        options:
        - handshake
        - transfer
        - longrtt
        - chacha20
        - multiplexing
        - retry
        - resumption
        - zerortt
        - http3
        - blackhole
        - keyupdate
        - ecn
        - amplificationlimit
        - handshakeloss 
        - transferloss
        - handshakecorruption
        - transfercorruption
        - ipv6
        - v2
        - goodput
        - crosstraffic

      client:
        type: choice
        description: Choose client
        options:
        - quic-go
        - ngtcp2
        - mvfst
        - quiche
        - kwik
        - picoquic
        - aioquic     
        - neqo
        - msquic
        - chrome
        - xquic
        - lsquic
        - quinn
        - s2n-quic
        - go-x-net
              
jobs:
  run:
    runs-on: ubuntu-24.04
  
    steps:
      - uses: actions/checkout@v4

      - name: Install tshark
        run: |
          sudo apt-get update
          sudo apt-get -y install tshark

      - name: Pull image
        run: |
          docker pull ghcr.io/${{ github.repository }}:local

      - name: Run
        run: |
          git clone https://github.com/quic-interop/quic-interop-runner
          cd quic-interop-runner
          pip install -r requirements.txt --break-system-packages
          python run.py --debug -l logs -r haproxy=ghcr.io/${{ github.repository }}:local -t ${{ github.event.inputs.testcase }} -c ${{ github.event.inputs.client }} -s haproxy

      - name: Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: quic-interop-runner/logs/





